{% set name = "notion-client" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a03a0cc0502292193527af07a3bd13e40eb2b1083b60dcc7d733baad2d2729fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - httpx >=0.15.0
    - python >=3.7

test:
  imports:
    - notion_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramnes/notion-sdk-py
  summary: Python client for the official Notion API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - pavel
