{% set name = "notion-client" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1e3ff65452ed29a2a044ec2236b38a430e09d8e18911c93ae16c6a2ae0744f60

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - httpx >=0.15.0
    - python >=3.7

test:
  imports:
    - notion_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramnes/notion-sdk-py
  summary: Python client for the official Notion API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - pavel
