{% set name = "notion-client" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e7ff32f733fdbe0f18a37f5d98ff665681e5b3c4dcf2faa6e602bb1b16a3b15d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - httpx >=0.15.0
    - python >=3.7

test:
  imports:
    - notion_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramnes/notion-sdk-py
  summary: Python client for the official Notion API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - pavel
