{% set name = "notion-client" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/notion-client-{{ version }}.tar.gz
  sha256: 7a6530c4cb631f04843bba62c0954a22e3e895a6a819314c6b170c83ed20188b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - httpx >=0.15.0
    - python >=3.6,<4.0

test:
  imports:
    - notion_client
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramnes/notion-sdk-py
  summary: Python client for the official Notion API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
